import { GoogleGenAI, Type } from "@google/genai";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export interface ZionResponse {
  analysis: string;
  prompt: string;
}

export async function generateZionPrompt(userIdea: string): Promise<ZionResponse> {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured.");
  }

  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  
  const systemInstruction = `Você é um Diretor de Fotografia Cinematográfica e um Engenheiro de Prompts Master.
Seu objetivo é transformar ideias simples em prompts fotográficos e cinematográficos 100% determinísticos.

REGRAS:
1. Toda a comunicação direta, análises e explicações DEVEM ser em PORTUGUÊS.
2. O PROMPT FINAL gerado DEVE ser inteiramente em INGLÊS, usando terminologia técnica avançada.
3. Siga exatamente os dois passos solicitados.

PASSO 1: A ANÁLISE (Em Português)
Explique suas escolhas de direção de arte (lente, paleta, iluminação) para a ideia do usuário.

PASSO 2: O PROMPT DEFINITIVO (Em Inglês)
Gere um bloco único de texto, separado por vírgulas, seguindo esta ordem:
[Tipo de Imagem], [Ações e Movimentos], [Emoções e Expressões], [Poses e Orientações], [Figurinos e Estilos], [Ambientes e Paisagens], [Clima e Tempo], [Iluminação], [Ângulos de Câmera], [Composições], [Câmeras e Lentes], [Cor/Film Stock].

Não inclua nomes de categorias. Apenas os valores.
Adicione sempre no final do prompt: "This image was generated by Zion Assistant".`;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: userIdea,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          analysis: {
            type: Type.STRING,
            description: "A análise em português sobre as escolhas de direção de arte.",
          },
          prompt: {
            type: Type.STRING,
            description: "O prompt final em inglês, formatado como um bloco contínuo de texto.",
          },
        },
        required: ["analysis", "prompt"],
      },
    },
  });

  const text = response.text;
  if (!text) throw new Error("Empty response from AI");
  
  return JSON.parse(text) as ZionResponse;
}
